---
title: "Resources"
bibliography: citations/REFERENCES.bib
favicon: images/headphones.JPG
output:
  distill::distill_article:
    toc: true
    toc_depth: 3
    css:
      - css/custom.css
description: |
  Resources.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source(file.path("R", "functions.R"))
library(distilltools)
```

```{r metathis, message=FALSE, warning=FALSE, include=FALSE}
library(metathis)
meta() %>%
  meta_description(
    "Resources"
  ) %>%
  meta_name("github-repo" = "donaldRwilliams/donaldRwilliams.github.io") %>%
  meta_viewport() %>%
  meta_social(
    title = "DRW: Resources",
    url = "https://donaldrwilliams.github.io/resources.html",
    image = "https://donaldrwilliams.github.io/images/fire2.png",
    image_alt = "A photo of DRW",
    og_type = "website",
    og_author = c("Donald R. Williams"),
    twitter_card_type = "summary",
    twitter_creator = "@wdonald_1985"
  )
```

# National Science Foundation Graduate Research Fellowship Materials

I received the NSFGRF in 2017.


```{r, echo=FALSE}
icon_link(
    icon = "fas fa-download",
    text = "Personal Statement",
    url  = "https://github.com/donaldRwilliams/donaldRwilliams.github.io/raw/main/files/donny_nsf_personal.pdf"
)

icon_link(
    icon = "fas fa-download",
    text = "Research Proposal",
    url  = "https://github.com/donaldRwilliams/donaldRwilliams.github.io/raw/main/files/donny_nsf_proposal.pdf"
)
```



