---
title: "Open-Source Software"
output:
  distill::distill_article:
    toc: true
    css:
      - css/custom.css
description: |
  Software that I have developed of the years.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source(file.path("R", "functions.R"))
library(distilltools)
```

```{r metathis, message=FALSE, warning=FALSE, include=FALSE}
library(metathis)
meta() %>%
  meta_description(
    "Open-Source Software"
  ) %>%
  meta_name("github-repo" = "donaldRwilliams/donaldRwilliams.github.io") %>%
  meta_viewport() %>%
  meta_social(
    title = "DRW: Software",
    url = "https://donaldrwilliams.github.io/software.html",
    image = "https://donaldrwilliams.github.io/images/donny_pic.jpeg",
    image_alt = "A photo of DRW",
    og_type = "website",
    og_author = c("Donald R. Williams"),
    twitter_card_type = "summary",
    twitter_creator = "@wdonald_1985"
  )
```

## Creator

### BGGM: Bayesian Gaussian Graphical Models
```{r, echo=FALSE}
icon_link(
    icon = "ai ai-google-scholar",
    text = "Downloads",
    url  = "http://cranlogs.r-pkg.org/badges/grand-total/BGGM"
)
```
## Contributor